### ISSUE TITLE
缺少java文件 无法编译

### ISSUE THREAD

**Issue by xmaxing** [crossoverJie/SSM#12]
BaseRequest.java CheckReqNo.java

**Comment by crossoverJie** [comment]
参考 https://github.com/crossoverJie/SSM-REQUEST-CHECK
可以本地`install`也可以在`pom`文件中去掉该依赖即可。

**Comment by crossoverJie** [comment]
详见 https://github.com/crossoverJie/SSM/blob/master/README.md
