### ISSUE TITLE
a

### ISSUE THREAD

**Issue by 757350134** [crossoverJie/SSM#13]
问题很多啊~跑不动

**Comment by crossoverJie** [comment]
你这样一说我不太清楚是什么问题。
如果是maven依赖的包没有可以查看 `README`。

**Comment by 757350134** [comment]
redisDemo 页面加载慢是我没有添加redis缓存吗？
service web  添加api 依赖还要加版本号，不然好像会报错？

**Comment by crossoverJie** [comment]
1. 页面加载慢建议你看下后台日志才能更好定位问题。
2. service web你指的是哪个依赖，通常来说每个依赖都需要加版本号，还有报的错是什么？
