### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by caisweet** [crossoverJie/SSM#14]
RedisController文件有一个依赖包路径是com.soecode.lyf.request.anotation.CheckReqNo，建议直接把文件加进项目里。

**Comment by crossoverJie** [comment]
我代码中并没有引用这个包。

引用的是：`import com.crossoverJie.request.anotation.CheckReqNo;`

你再核对下。

**Comment by caisweet** [comment]
恩，是我看错了。在之前的issue也有人提过缺少依赖包的问题，可以关闭这个了，谢谢答复。
