### ISSUE TITLE
怎么建个人博客啊

### ISSUE THREAD

**Issue by wszagq** [crossoverJie/SSM#2]
整个教程交一下 怎么建一个自己的博客啊

**Comment by crossoverJie** [comment]
这个搜索github搭建博客有很多。

**Comment by wszagq** [comment]
你这个博客也是在github上的啊?

**Comment by crossoverJie** [comment]
你说的是主页http://www.crossoverjie.top?还是 http://crossoverjie.top?

**Comment by wszagq** [comment]
第二个，没有WWW的那个

**Comment by crossoverJie** [comment]
用hexo生成的 然后用github部署的 具体你可以Google

**Comment by wszagq** [comment]
get√
