### ISSUE TITLE
小弟新手，导入项目运行不起来是什么原因

### ISSUE THREAD

**Issue by dedeTao** [crossoverJie/SSM#24]
### 报很多类找不到

idea也不提示解决方案，就是类找不到，我该怎么解决

**Comment by crossoverJie** [comment]
兄弟，你至少得提供一个异常吧，或者是截图吧。

**就是类找不到**  这样的描述没人能帮你解决。

**Comment by crossoverJie** [comment]
建议看下这个 #17 这个 Issues，良好的提问可以给双方带来好处。

**Comment by dedeTao** [comment]
没报什么错，第一次导入项目，shizhe是这个样子
我是新手多多见谅

**Comment by dedeTao** [comment]
![123](https://user-images.githubusercontent.com/15975203/37516449-1b3d99e8-2949-11e8-9b6d-373cbc6c68b5.png)
这个y样子

**Comment by dedeTao** [comment]
我是不是没有配置什么或者少做了步骤？
我现在只是通过open打开了项目路径，然后没有任何的提示

**Comment by crossoverJie** [comment]
你看是否能够成功编译？
