### ISSUE TITLE
你好，我这里还缺少一个jar包，是什么情况？

### ISSUE THREAD

**Issue by williamHappy** [crossoverJie/SSM#26]
![image](https://user-images.githubusercontent.com/19304825/38464695-a24714ca-3b44-11e8-891c-72ce902b94d5.png)

**Comment by crossoverJie** [comment]
@williamHappy 由于 `SSM-TRACE-FILTER` 这个包并没有传到 maven 中央厂库，所以下载不到。

参考：

https://github.com/crossoverJie/SSM/blob/master/README-ZH.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

这个可以解决。

**Comment by williamHappy** [comment]
![image](https://user-images.githubusercontent.com/19304825/38465683-88b5c300-3b51-11e8-8438-c38073d9abd6.png)
这两个jar包 我是有都安装到了本地，缺少的不是SSM-TRACE-FILTER这么jar包吗，这个jar是没有的

**Comment by crossoverJie** [comment]
不好意思 `SSM-TRACE-FILTER` 这个包是 https://github.com/crossoverJie/SSM-DUBBO-FILTER  这个项目的，文档我再完善一下。

**Comment by williamHappy** [comment]
好的，那我把你的SSM-DUBBO-FILTER这个再安装下，还有就是你的两个数据库ssm和ssm2都是一样的是吗

**Comment by crossoverJie** [comment]
SQL 脚本见这里:

https://github.com/crossoverJie/SSM/tree/master/doc/sql

**Comment by williamHappy** [comment]
好的吧,刚刚就一个sql，我还以为一个是备份的数据源呢 555

**Comment by williamHappy** [comment]
多谢了

**Comment by crossoverJie** [comment]
没事，以前忘记更新了。
