### ISSUE TITLE
web搜查按钮保存，

### ISSUE THREAD

**Issue by astali** [crossoverJie/SSM#30]
**在提交issue之前请回答以下问题，谢谢!**

### 你使用的是哪个版本 
2.0.1
### 预期结果
Service启动成功，web启动成功，
### 实际结果
Service启动失败，jar冲突保存， 希望博主能加上jar包的版本号，
web启动成功，搜查报错
nested exception is java.lang.UnsupportedClassVersionError: org/apache/lucene/store/Directory : Unsupported major.minor version 52.0 (unable to load class org.apache.lucene.store.Directory)
### 其他相关信息

**Comment by crossoverJie** [comment]
文档后续会尽量完善。
