### ISSUE TITLE
您好，无处寻找私信您的方式，只能给您发issue了

### ISSUE THREAD

**Issue by shiqikai** [crossoverJie/SSM#31]
请问您的博客有模板吗？  还是自己写的啊？
盼回复，谢谢！

**Comment by crossoverJie** [comment]
@shiqikai 简书上也是你发的哈？

个人博客是用 Hexo 做的。

你可以搜索下 Hexo + GitHub 就知道了。

> 我的个人邮箱项目下有，个人主页也写的有，可以发邮件的。

**Comment by shiqikai** [comment]
@crossoverJie 谢谢谢谢！

**Comment by crossoverJie** [comment]
@shiqikai 不客气。
