### ISSUE TITLE
启动redis异常

### ISSUE THREAD

**Issue by JonDai** [crossoverJie/SSM#32]
**在提交issue之前请回答以下问题，谢谢!**

版本：最新版本
已检查确认redis ip和密码 正确无误，以及redis正常启动。
![image](https://user-images.githubusercontent.com/15091781/40043360-d6005414-5856-11e8-8e95-81d8f5ccd49c.png)

不知还有哪些地方没有配置到位。  望提示！

**Comment by JonDai** [comment]
master 版本。

**Comment by crossoverJie** [comment]
@JonDai 启动的是哪个项目？Service 还是 Web？怎么启动的也描述下呢。

**Comment by JonDai** [comment]
是否需要先启动server？

**Comment by crossoverJie** [comment]
@JonDai 是启动的 `SSM-SECONDS-KILL-WEB` 这个模块嘛？看你这个异常是包不全导致的，建议你按照这个脚本 clean package 之后再试试。

[https://github.com/crossoverJie/SSM/blob/master/script/build-seconds-kill-web.sh#L30-L32](https://github.com/crossoverJie/SSM/blob/master/script/build-seconds-kill-web.sh#L30-L32)
