### ISSUE TITLE
SSM-SECOND-KILL-API是用来干嘛的？

### ISSUE THREAD

**Issue by Malop** [crossoverJie/SSM#35]
请问SSM-SECOND-KILL-API是提供给外部service层的实现，那SSM-SECOND-KILL-SERVICE里有两个OrderServiceImpl，
(a)一个实现本身service包下的OrderService，
(b)调用service包下的OrderService再实现，这两者有什么区别呢？
且b里的实现com.crossoverJie.seconds.kill.api.impl看注释是需要暴露的接口(这个不懂，跟SSM(十三)是一个意思吗？)，那SSM-SECOND-KILL-API里的好像并没有被实现吧？那这个API是用来干嘛的？

**Comment by crossoverJie** [comment]
@Malop 

一点小建议：

> 提问的格式稍微调整下，方便阅读(尽量采用 `Markdown` 书写)。

`SSM-SECOND-KILL-API` 这个模块通常是提供给外部使用。

比如有人需要调用我(SSM-SECONDS-KILL-SERVICE)提供的 `dubbo` 服务。

既然提供了服务，这里的 API 模块，那就得需要具体的实现。

所以 `com.crossoverJie.seconds.kill.api.impl.OrderServiceImpl` 就是实现上文的 API 模块。

在 `SSM-SECONDS-KILL-SERVICE` 也存在一个 `OrderService` 的原因是我名字取重复了，这个 `OrderService` 就是一个纯粹的三层模型中的数据库层，用于真正操作数据。

和 API 模块中的 OrderService **没有任何关系**。

不知道这样解释能理解嘛。

**Comment by Malop** [comment]
非常感谢，今天又仔细看了下代码，完全理解了，对dubbo不太懂，所以对这种微服务的调用还比较生疏。

    
        
            
                
                    
                        
                    
                    
                        
                            毛伟鹏
                            
                            
                                
                                    邮箱：mwp1107@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
在2018年06月20日 15:47，crossoverJie 写道： @Malop
一点小建议：

提问的格式稍微调整下，方便阅读(尽量采用 Markdown 书写)。

SSM-SECOND-KILL-API 这个模块通常是提供给外部使用。
比如有人需要调用我(SSM-SECONDS-KILL-SERVICE)提供的 dubbo 服务。
既然提供了服务，这里的 API 模块，那就得需要具体的实现。
所以 com.crossoverJie.seconds.kill.api.impl.OrderServiceImpl 就是实现上文的 API 模块。
在 SSM-SECONDS-KILL-SERVICE 也存在一个 OrderService 的原因是我名字取重复了，这个 OrderService 就是一个纯粹的三层模型中的数据库层，用于真正操作数据。
和 API 模块中的 OrderService 没有任何关系。
不知道这样解释能理解嘛。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/crossoverJie/SSM/issues/35#issuecomment-398656629","url":"https://github.com/crossoverJie/SSM/issues/35#issuecomment-398656629","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crossoverJie/SSM","title":"crossoverJie/SSM","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/crossoverJie/SSM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@crossoverJie in #35: @Malop \r\n\r\n一点小建议：\r\n\r\n\u003e 提问的格式稍微调整下，方便阅读(尽量采用 `Markdown` 书写)。\r\n\r\n`SSM-SECOND-KILL-API` 这个模块通常是提供给外部使用。\r\n\r\n比如有人需要调用我(SSM-SECONDS-KILL-SERVICE)提供的 `dubbo` 服务。\r\n\r\n既然提供了服务，这里的 API 模块，那就得需要具体的实现。\r\n\r\n所以 `com.crossoverJie.seconds.kill.api.impl.OrderServiceImpl` 就是实现上文的 API 模块。\r\n\r\n在 `SSM-SECONDS-KILL-SERVICE` 也存在一个 `OrderService` 的原因是我名字取重复了，这个 `OrderService` 就是一个纯粹的三层模型中的数据库层，用于真正操作数据。\r\n\r\n和 API 模块中的 OrderService **没有任何关系**。\r\n\r\n不知道这样解释能理解嘛。"}],"action":{"name":"View Issue","url":"https://github.com/crossoverJie/SSM/issues/35#issuecomment-398656629"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [crossoverJie/SSM] SSM-SECOND-KILL-API是用来干嘛的？ (#35)",
"sections": [
{
"text": "",
"activityTitle": "**crossoverJie**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@crossoverJie",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"crossoverJie/SSM\",\n\"issueId\": 35,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"crossoverJie/SSM\",\n\"issueId\": 35\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/crossoverJie/SSM/issues/35#issuecomment-398656629"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 347799685\n}"
}
],
"themeColor": "26292E"
}

**Comment by crossoverJie** [comment]
@Malop 嗯 没问题我就 close 咯。
