### ISSUE TITLE
Please check your account security

### ISSUE THREAD

**Issue by yasuokav** [crossoverJie/SSM#36]
There was some malware uploaded to releases via your account.
* https://github.com/crossoverJie/SSM/releases
* https://github.com/crossoverJie/distributed-redis-tool/releases
* https://github.com/crossoverJie/SSM-DUBBO-HTTP/releases
* https://github.com/crossoverJie/netty-action/releases
* https://github.com/crossoverJie/springboot-cloud/releases
* https://github.com/V2Git/shadowsocks/releases
* https://github.com/V2Git/v2ex/releases
* https://github.com/V2Git/How-To-Ask-Questions-The-Smart-Way/releases
* https://github.com/V2Git/Awesome-V2EX/releases
* https://github.com/V2Git/WeiboPicBed/releases
* https://github.com/V2Git/HyperMD/releases
* https://github.com/V2Git/hacknical/releases
* https://github.com/V2Git/SpaceVim/releases
* https://github.com/V2Git/bilibili-live-kit/releases
* https://github.com/V2Git/shadowsocks-over-websocket/releases
* https://github.com/V2Git/EQGRP/releases
* https://github.com/V2Git/musicbox/releases
* https://github.com/V2Git/nginx-http-echo-module/releases
* https://github.com/V2Git/free-programming-books/releases
* https://github.com/V2Git/sibi/releases
* https://github.com/V2Git/shadowsocks-rss/releases
* https://github.com/V2Git/README/releases
* https://github.com/V2Git/wechat_jump_game/releases
* https://github.com/V2Git/91porn/releases
* https://github.com/V2Git/FEBS/releases
* https://github.com/junicorn/mario-sample/releases
* https://github.com/junicorn/jianzhioffer/releases

**Comment by crossoverJie** [comment]
@yasuokav 

thx.

I have found this problem.

But I don't know why.

I already gave GitHub feedback.

Do you know something about this?

**Comment by yasuokav** [comment]
@crossoverJie 
I have no idea actually.
