### ISSUE TITLE
com.crossoverJie.request.anotation不存在

### ISSUE THREAD

**Issue by LittleBeanW** [crossoverJie/SSM#41]
在提交issue之前请回答以下问题，谢谢!
你使用的是哪个版本
**master**
预期结果
**运行错误**
其他相关信息
**Error:(8, 42) java: 程序包com.crossoverJie.request.anotation不存在**
请问一下这个问题怎么处理呢

**Comment by crossoverJie** [comment]
请查看首页以及以前的 issue 都有提到，这个项目没有暂时没有经历维护了。
