### ISSUE TITLE
两个XML配置文件的问题

### ISSUE THREAD

**Issue by wszagq** [crossoverJie/SSM#5]
5.spring-mvc.xml 跟6. spring-mybatis.xml 我看前面的配置都是一样的 扫描 controller  就是mybatis.xml里面多了 关于数据的配置 我想这俩 可不可以写在一个里面 还有 你那个SSM1的教程里 没有写WEB.XML的相关配置啊。。。可否补全edit一下啊。

**Comment by crossoverJie** [comment]
邮件已回。
