### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by lancelot801** [crossoverJie/SSM#7]
![qq 20170118165401](https://cloud.githubusercontent.com/assets/18180589/22057225/bf71d0c6-dd9e-11e6-891d-7fa3ff876f0e.jpg)
我把项目run as --》run on server 弹出这个页面  输入 crossoverJie 123456 / jack abc123都不能登录，而且控制台报错，该怎么解决？

![console](https://cloud.githubusercontent.com/assets/18180589/22057300/1ac3338e-dd9f-11e6-9250-c6ca71539630.jpg)

**Comment by crossoverJie** [comment]
看错误啊 空指针了嘛  Myrealm.java 55行报错了。
